"""Generate the self-contained fig-brush synthetic reference example.

The image and the values in this directory are deliberately synthetic.  They
are useful for demonstrating the reference-only workflow without publishing a
paper figure or any private measurements.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parent
WIDTH, HEIGHT = 1200, 760
FRAME = (128, 145, 1090, 625)
X_VALUES = [float(value) for value in range(11)]


def _series_values(x: float) -> tuple[float, float]:
    """Return two deterministic, non-scientific curves for the example."""
    rising = 0.18 + 0.74 * (1.0 - math.exp(-x / 3.4)) + 0.018 * math.sin(1.45 * x)
    falling = 0.87 - 0.055 * x + 0.022 * math.cos(1.2 * x)
    return round(rising, 5), round(falling, 5)


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates: list[Path] = []
    if os.name == "nt":
        windows_fonts = Path(os.environ.get("WINDIR", "")) / "Fonts"
        candidates.extend([
            windows_fonts / ("arialbd.ttf" if bold else "arial.ttf"),
            windows_fonts / ("segoeuib.ttf" if bold else "segoeui.ttf"),
        ])
    else:
        candidates.append(Path("/usr/share/fonts/truetype/dejavu") / ("DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"))
    for candidate in candidates:
        if candidate.is_file():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def _points(values: Iterable[float], x0: float, x1: float, y0: float, y1: float) -> list[tuple[float, float]]:
    return [(x0 + (x / 10.0) * (x1 - x0), y1 - (y / 1.2) * (y1 - y0)) for x, y in zip(X_VALUES, values)]


def _draw_reference(path: Path) -> None:
    scale = 3
    image = Image.new("RGB", (WIDTH * scale, HEIGHT * scale), "white")
    draw = ImageDraw.Draw(image)

    def xy(value: float) -> int:
        return int(round(value * scale))

    def box(values: tuple[float, float, float, float]) -> tuple[int, int, int, int]:
        return tuple(xy(value) for value in values)  # type: ignore[return-value]

    colors = {
        "ink": "#172033",
        "muted": "#667085",
        "grid": "#E6EAF0",
        "frame": "#94A3B8",
        "blue": "#2563EB",
        "orange": "#F97316",
        "badge": "#EFF6FF",
        "badge_ink": "#1D4ED8",
    }
    left, top, right, bottom = FRAME

    draw.text((xy(left), xy(37)), "Synthetic reference reconstruction", font=_font(xy(30), True), fill=colors["ink"])
    draw.text(
        (xy(left), xy(86)),
        "Two editable line + scatter series generated by fig-brush",
        font=_font(xy(17)),
        fill=colors["muted"],
    )
    badge = (860, 39, 1090, 82)
    draw.rounded_rectangle(box(badge), radius=xy(12), fill=colors["badge"], outline="#BFDBFE", width=xy(1))
    draw.text((xy(878), xy(51)), "SYNTHETIC • NOT RESEARCH DATA", font=_font(xy(13), True), fill=colors["badge_ink"])

    # Grid and axes.
    for tick in range(0, 11):
        x = left + (right - left) * tick / 10
        draw.line((xy(x), xy(top), xy(x), xy(bottom)), fill=colors["grid"], width=xy(1))
    for tick in range(0, 7):
        value = tick * 0.2
        y = bottom - (bottom - top) * value / 1.2
        draw.line((xy(left), xy(y), xy(right), xy(y)), fill=colors["grid"], width=xy(1))
    draw.rectangle(box(FRAME), outline=colors["frame"], width=xy(2))

    tick_font = _font(xy(14))
    for tick in range(0, 11, 2):
        x = left + (right - left) * tick / 10
        label = str(tick)
        bounds = draw.textbbox((0, 0), label, font=tick_font)
        draw.text((xy(x) - (bounds[2] - bounds[0]) // 2, xy(bottom + 14)), label, font=tick_font, fill=colors["muted"])
    for tick in range(0, 7):
        value = tick * 0.2
        y = bottom - (bottom - top) * value / 1.2
        label = f"{value:.1f}"
        bounds = draw.textbbox((0, 0), label, font=tick_font)
        draw.text((xy(left - 18) - (bounds[2] - bounds[0]), xy(y) - (bounds[3] - bounds[1]) // 2), label, font=tick_font, fill=colors["muted"])

    axis_font = _font(xy(17), True)
    x_label = "Time (a.u.)"
    bounds = draw.textbbox((0, 0), x_label, font=axis_font)
    draw.text((xy((left + right) / 2) - (bounds[2] - bounds[0]) // 2, xy(681)), x_label, font=axis_font, fill=colors["ink"])
    # Rotating text keeps the y-axis title readable while matching common
    # scientific figure layouts.
    y_title = Image.new("RGBA", (xy(260), xy(36)), (255, 255, 255, 0))
    y_draw = ImageDraw.Draw(y_title)
    y_draw.text((xy(8), 0), "Normalized response", font=axis_font, fill=colors["ink"])
    y_title = y_title.rotate(90, expand=True)
    image.paste(y_title, (xy(20), xy(300)), y_title)

    rising = [_series_values(x)[0] for x in X_VALUES]
    falling = [_series_values(x)[1] for x in X_VALUES]
    # Dense traces make the editable template's line role clear.  Markers are
    # kept at the eleven visible observations below.
    dense_x = [10.0 * index / 120 for index in range(121)]
    dense_rising = [_series_values(x)[0] for x in dense_x]
    dense_falling = [_series_values(x)[1] for x in dense_x]
    for values, color in ((dense_rising, colors["blue"]), (dense_falling, colors["orange"])):
        coords = [
            (xy(left + (x / 10.0) * (right - left)), xy(bottom - (y / 1.2) * (bottom - top)))
            for x, y in zip(dense_x, values)
        ]
        draw.line(coords, fill=color, width=xy(3), joint="curve")
    for values, color, marker in ((rising, colors["blue"], "circle"), (falling, colors["orange"], "square")):
        coords = _points(values, left, right, top, bottom)
        for px, py in coords:
            if marker == "circle":
                draw.ellipse(box((px - 6, py - 6, px + 6, py + 6)), fill="white", outline=color, width=xy(3))
                draw.ellipse(box((px - 3, py - 3, px + 3, py + 3)), fill=color)
            else:
                draw.rounded_rectangle(box((px - 6, py - 6, px + 6, py + 6)), radius=xy(2), fill="white", outline=color, width=xy(3))
                draw.rectangle(box((px - 3, py - 3, px + 3, py + 3)), fill=color)

    # Legend, with each swatch showing both the line and marker semantics.
    legend_x, legend_y = 806, 172
    draw.rounded_rectangle(box((legend_x, legend_y, 1068, legend_y + 102)), radius=xy(9), fill="white", outline="#D0D5DD", width=xy(1))
    for index, (label, color, marker) in enumerate((("Increasing response", colors["blue"], "circle"), ("Decreasing response", colors["orange"], "square"))):
        y = legend_y + 31 + index * 35
        draw.line((xy(826), xy(y), xy(862), xy(y)), fill=color, width=xy(3))
        if marker == "circle":
            draw.ellipse(box((844, y - 6, 856, y + 6)), fill="white", outline=color, width=xy(2))
            draw.ellipse(box((848, y - 2, 852, y + 2)), fill=color)
        else:
            draw.rectangle(box((844, y - 6, 856, y + 6)), fill="white", outline=color, width=xy(2))
            draw.rectangle(box((848, y - 2, 852, y + 2)), fill=color)
        draw.text((xy(876), xy(y - 11)), label, font=_font(xy(15)), fill=colors["ink"])

    footer = "Placeholder values are synthetic and intentionally approximate; they are not original research data."
    draw.text((xy(left), xy(724)), footer, font=_font(xy(13)), fill=colors["muted"])
    image.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS).save(path)


def _template_spec() -> dict:
    marker_x = X_VALUES
    marker_a = [_series_values(x)[0] for x in marker_x]
    marker_b = [_series_values(x)[1] for x in marker_x]
    dense_x = [round(10.0 * index / 120, 5) for index in range(121)]
    dense_a = [_series_values(x)[0] for x in dense_x]
    dense_b = [_series_values(x)[1] for x in dense_x]
    return {
        "schema_version": "2.0",
        "mode": "reference_template",
        "canvas": {"width_px": WIDTH, "height_px": HEIGHT, "font_reference_px": 17, "font_anchor_pt": 10},
        "style": {
            "page_aspect_ratio": WIDTH / HEIGHT,
            "base_font_pt": 10,
            "tick_label_font_pt": 9,
            "plot_frame": {"left": 10.67, "top": 19.08, "right": 90.83, "bottom": 82.24},
        },
        "scientific_context": {
            "title": "Synthetic two-series line and scatter example",
            "description": "Deterministic demonstration data generated by fig-brush; not research data.",
            "contract_version": "0.3.1",
        },
        "data_policy": {
            "source": "reference_image_only",
            "private_data_requested": False,
            "original_data_recovered": False,
            "provenance": "Synthetic placeholder values generated for the fig-brush example; not original research data.",
        },
        "placeholder_policy": {
            "mode": "approximate_visual",
            "numeric_significant_digits": 3,
            "fit_dense_points": 120,
            "preserve_axis_bounds": True,
            "preserve_marker_count": True,
        },
        "panels": [
            {
                "id": "MainPlot",
                "frame_px": list(FRAME),
                "axes": {
                    "x": {"min": 0, "max": 10, "scale": "linear", "title": "Time (a.u.)"},
                    "y": {"min": 0, "max": 1.2, "scale": "linear", "title": "Normalized response"},
                },
                "legend": {"visible": True, "position": "top_right", "title": "Synthetic series"},
                "series": [
                    {
                        "id": "SeriesA",
                        "name": "Increasing response",
                        "kind": "line_symbol",
                        "role": "synthetic marker + line",
                        "data": {"x": marker_x, "y": marker_a},
                        "marker_data": {"x": marker_x, "y": marker_a},
                        "line_data": {"x": dense_x, "y": dense_a},
                        "style": {"color": "#2563EB", "symbol": 2, "symbol_size": 8, "symbol_interior": 1, "line_width": 2.2},
                    },
                    {
                        "id": "SeriesB",
                        "name": "Decreasing response",
                        "kind": "line_symbol",
                        "role": "synthetic marker + line",
                        "data": {"x": marker_x, "y": marker_b},
                        "marker_data": {"x": marker_x, "y": marker_b},
                        "line_data": {"x": dense_x, "y": dense_b},
                        "style": {"color": "#F97316", "symbol": 1, "symbol_size": 8, "symbol_interior": 1, "line_width": 2.2},
                    },
                ],
            }
        ],
        "output": {"preview_formats": ["png"], "preview_name": "reference.png"},
        "example": {
            "name": "fig-brush synthetic example",
            "version": "0.3.1",
            "author": "Petey Yu",
            "license": "Apache-2.0",
            "not_research_data": True,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the fig-brush synthetic reference image and TemplateSpec.")
    parser.add_argument("--output-dir", type=Path, default=ROOT, help="Directory receiving reference.png and template_spec.json")
    args = parser.parse_args()
    output = args.output_dir.expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)
    _draw_reference(output / "reference.png")
    (output / "template_spec.json").write_text(json.dumps(_template_spec(), indent=2) + "\n", encoding="utf-8")
    print(f"Generated {output / 'reference.png'}")
    print(f"Generated {output / 'template_spec.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
